### ISSUE TITLE
metadata.csv

### ISSUE THREAD

**Issue by bigwiz83** [allenai/s2orc-doc2json#10]
Hello, 
I think this is great work!

I wonder if 'metadata.csv' is automatically generated as like CORD-19.
Thanks in advance.

**Comment by lucylw** [comment]
Hi, no, it is not. The metadata for CORD-19 (and S2ORC) are derived from publishers and other sources. This utility is meant to be a standalone tool for processing individual PDFs and documents. For metadata, if you have an identifier associated with a paper, you can look into https://api.semanticscholar.org/ for getting the corresponding metadata from the Semantic Scholar database.

**Comment by bigwiz83** [comment]
Thanks for the reply. It really helps.
