### ISSUE TITLE
Could this PDF-Convert tool used in Colab environment with conda-colab?

### ISSUE THREAD

**Issue by Olivia-fsm** [allenai/s2orc-doc2json#14]
It stuck at 87% for a very long time when I run `setup_grobid.sh`... 
Thanks for any responses in advance!

**Comment by lucylw** [comment]
Please see this: [https://github.com/allenai/s2orc-doc2json#pdf-processing](https://github.com/allenai/s2orc-doc2json#pdf-processing) 

`Don't worry if it gets stuck at 87%; this is normal and means Grobid is ready to process PDFs.`

This means you can start processing PDFs in a different terminal session.
